### ISSUE TITLE
Error in test_roi_pooling_conv.py

### ISSUE THREAD

**Issue by yasserabbass** [yhenon/keras-spp#2] opened 2017-01-16 21:31 UTC
When I tried to run the script it gave me the error
AttributeError: 'RoiPoolingConv' object has no attribute 'pool_list'

Also can you please create an example for using the scripts

thanks

**Comment by yhenon** [comment] 2017-01-17 22:03
Thanks for reporting this. I'm now aware of some issues with the tensorflow backend, it should be fixed over the next day or two.

**Comment by fferroni** [comment] 2017-01-18 16:43
Is RoiPooling essentially a "flattened" version of RoiPoolingConv, for each RoI ? In other words, it returns the various RoI feature vectors rather than the RoI feature maps?

**Comment by yhenon** [comment] 2017-01-18 16:56
@fferroni yes that's correct. 
One advantage of RoiPooling of it is that you can pool at multiple sizes since the output is all flat. With RoiPooling, you can for example have a 1x1, a 2x2 and a 4x4, all flattened into a 1+4+16=21 length array.
But with RoiPoolingConv, if you have a 7x7 output, you can't have a different size one, since your array would be uneven.

**Comment by fferroni** [comment] 2017-01-18 17:04
Thanks. Yes, that sounds nice.
Given that you mention i.e. Fast RCNN in your readme, the output of this RoiPooling layer would then be passed through some FC layers and split into a softmax output and a bbox regressor output. But in Keras, how do you do this for multiple ROI? The output of this RoiPooling would be (None, nb_roi, nb_channels * num_outputs_per_channel) but the classification and regression needs to be done for each roi.

**Comment by yhenon** [comment] 2017-01-18 17:11
Hey,
The trick is to use `TimeDistributed`, which will apply it as you want. It's kind of awkward, but I see no other way to do it. I am working on a prototype faster-rcnn implementation right now, you can see the model definition [here](https://github.com/yhenon/keras-frcnn/blob/master/resnet.py)
Basically the layer look like this:

    def classifier(base_layers,input_rois,num_rois,nb_classes = 21):

        pooling_regions = 7

        out_roi_pool = RoiPoolingConv(pooling_regions, num_rois)([base_layers,input_rois])
        out_class  = TimeDistributed(Convolution2D(...))(out_roi_pool)
        ...
        out_class  = TimeDistributed(Flatten())(out_class)
        out_class  = TimeDistributed(Dense(nb_classes,activation='softmax'),name='dense_{}'.format(nb_classes))(out_class)

        return (out_class)

For RoiPooling, use `TimeDistributed(Dense(...))` instead of `TimeDistributed(Convolution2D(...))`

**Comment by fferroni** [comment] 2017-01-18 17:12
Ha! You beat me to it ;-)

**Comment by yhenon** [comment] 2017-01-18 17:31
Ha not really, mine is still very much a work in progress. It is quite a large task, I would certainly be interested if you want to collaborate or submit some pull requests.

**Comment by yhenon** [comment] 2017-03-06 16:23
I've finally fixed this. All test should now pass for both the theano and tensorflow backend (tested with keras 1.2.2, theano 0.8.2, tensorflow 1.0.0). Note that there are small differences in how rounding is handled by default, so results may not be exactly reproducible between pure numpy vs theano vs tensorflow is pooling sized that don't divide exactly (i.e. pooling size 16 into a size 3).

For a more complete example on using these layers, see the work on frcnn I've begun here:
https://github.com/yhenon/keras-frcnn

Please feel free to reopen this if you have issues.

**Closed by yhenon** 2017-03-06 16:23 UTC

**Comment by kirk86** [comment] 2017-03-09 22:11
@yhenon are u planning to do a pull request to keras?
